// 2.0.0 prompt 53 Phase 2: the eager game-split scan now splits on a
// top-level RESULT TOKEN as well as on a tag roster. Before this change bare
// (roster-less) multi-game input silently collapsed into one game whose
// movetext-raw was the whole string and whose second game vanished with no
// error. These asserts pin down the new splitting behavior, including the
// false-positive guards (result inside a comment/variation, "1..." is not a
// restart, a FEN-started game is not a restart).
#import "/lib.typ": game, games, mainline

// -- result token terminates a game (bare movetext, no rosters at all) ------
#let bare = games("1. e4 e5 2. Nf3 *\n\n1. d4 d5 2. c4 *")
#assert(bare.len() == 2, message: "bare result-terminated input -> two games")
#assert(mainline(bare.at(0)) == ("e4", "e5", "Nf3"), message: "first game mainline")
#assert(mainline(bare.at(1)) == ("d4", "d5", "c4"), message: "second game mainline")
#assert(bare.at(0).result == "*", message: "first game result")
#assert(bare.at(1).result == "*", message: "second game result")
#assert(bare.at(0).movetext-raw == "1. e4 e5 2. Nf3 *", message: "first game movetext-raw includes its own result token")
#assert(bare.at(1).movetext-raw == "1. d4 d5 2. c4 *", message: "second game movetext-raw includes its own result token")

// -- roster-after-result: the two separators compose -------------------------
#let mixed = games("1. e4 e5 * [White \"B\"] 1. d4 1-0")
#assert(mixed.len() == 2, message: "result-then-roster input -> two games")
#assert(mixed.at(0).result == "*", message: "first game result (mixed)")
#assert(mixed.at(1).result == "1-0", message: "second game result (mixed)")
#assert(mixed.at(0).movetext-raw == "1. e4 e5 *", message: "first game movetext-raw (mixed)")
#assert(mixed.at(1).movetext-raw == "1. d4 1-0", message: "second game movetext-raw (mixed)")

// -- roster split still works unchanged --------------------------------------
#let rostered = games("[White \"A\"] 1. e4 e5 *\n\n[White \"B\"] 1. d4 *")
#assert(rostered.len() == 2, message: "roster split unchanged")

// -- a result token INSIDE A COMMENT is not a separator ----------------------
#let commented = games("1. e4 e5 {1-0 was agreed} 2. Nf3 *")
#assert(commented.len() == 1, message: "result token inside a comment must not split")
#assert(mainline(commented.first()) == ("e4", "e5", "Nf3"), message: "mainline unaffected by the in-comment result token")

// -- a result token INSIDE A VARIATION neither splits nor sets the result ----
#let varied = games("1. e4 (1. d4 1-0) e5 *")
#assert(varied.len() == 1, message: "result token inside a variation must not split")
#assert(varied.first().result == "*", message: "result must come from the top-level token, not the variation's")
#assert(varied.first().movetext-raw == "1. e4 (1. d4 1-0) e5 *", message: "movetext-raw is the whole string, variation included")

// -- "1..." (black-continuation marker) is NOT a restart ---------------------
#let continuation = games("1. e4 (1. d4 d5) 1... e5 2. Nf3 1-0")
#assert(continuation.len() == 1, message: "a black-continuation marker after a variation must not be treated as a restart")
#assert(mainline(continuation.first()) == ("e4", "e5", "Nf3"), message: "mainline survives the false-positive guard")

// -- a FEN-started game (opening move number > 1) does not trip the guard ---
#let fen-start = games("[FEN \"rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2\"][SetUp \"1\"] 2... Nc6 3. Bb5 *")
#assert(fen-start.len() == 1, message: "FEN-start game must not trip the restart check")
#assert(mainline(fen-start.first()) == ("Nc6", "Bb5"), message: "FEN-start mainline")

// -- trailer merge: a span with no roster AND no move-like token is not a ---
// game -- it is a trailer (closing banner / comment / stray duplicate
// result) and must be merged back into the game it follows, not emitted as a
// phantom game. This is the review's top finding: it used to error with
// "input contains 2 games" on a perfectly ordinary file.
#let trailed = games("1. e4 e5 1-0\n; generated by SomeTool")
#assert(trailed.len() == 1, message: "trailing comment line must not become a phantom game")
#assert(trailed.first().result == "1-0", message: "trailer merge: result")
#assert(trailed.first().movetext-raw == "1. e4 e5 1-0\n; generated by SomeTool", message: "trailer merge: trailer stays IN movetext-raw, verbatim")

#let two-with-trailer = games("1. e4 1-0 {gg} [Event \"B\"] 1. d4 0-1")
#assert(two-with-trailer.len() == 2, message: "trailer-then-roster: still two games, not three")
#assert(two-with-trailer.at(0).result == "1-0", message: "trailer-then-roster: first result")
#assert(two-with-trailer.at(0).movetext-raw == "1. e4 1-0 {gg}", message: "trailer-then-roster: first raw includes the trailing comment")
#assert(two-with-trailer.at(0).tags == (:), message: "trailer-then-roster: first game has no tags")
#assert(two-with-trailer.at(1).result == "0-1", message: "trailer-then-roster: second result")
#assert(two-with-trailer.at(1).movetext-raw == "1. d4 0-1", message: "trailer-then-roster: second raw")
#assert(two-with-trailer.at(1).tags.len() == 1, message: "trailer-then-roster: second game has one tag")

#let dup-result = games("1. e4 e5 1-0 1-0")
#assert(dup-result.len() == 1, message: "a stray duplicate result token is a trailer, not a second game")
#assert(dup-result.first().result == "1-0", message: "dup-result: result stays the first token")
#assert(dup-result.first().movetext-raw == "1. e4 e5 1-0 1-0", message: "dup-result: raw includes the duplicate")

// A trailer with no preceding game is still emitted -- games() must never
// return an empty array.
#let only-trailer = games("{just a comment}")
#assert(only-trailer.len() == 1, message: "a lone trailer must still produce one game, never an empty array")

// The exact regression the review caught: a normal single-game file with a
// closing comment banner must NOT error.
#let regression = game("[Event \"T\"]\n1. e4 e5 1-0\n\n; end of file\n")
#assert(regression.result == "1-0", message: "single game with trailing comment banner must parse cleanly")

// The eager split path must stay clean for leading prose before the movetext
// -- reading tags/results should never touch move semantics. (mainline() on
// this DOES error -- that's fine, and unchanged from before this fix; only
// games() itself must stay silent.)
#let prose = games("Game 1. Kasparov - Karpov\n1. e4 e5 *")
#assert(prose.len() == 1, message: "leading prose before movetext must not trip the eager scan")

= multi-game split OK
